id: 6c827f4e6bf344cdb0075ed121da4839
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_122-Wisdom_at_the_Hour_of_Death-v1
  language: en
  author: ''
  volume: {}
